name: SAST-python-demo
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run build and tests
      if: succeeds()
      run: |
        # your build and test commands here
    - name: List installed libraries
      run: |
        pip freeze > requirements.txt
    - name: Add SonarQube details
      uses: sonarqube-action@v1
      with:
        credentials_token: ${{ secrets.SONAR_TOKEN }}
        sonarhost: 'http://sonarqube.example.com'
        sonarprojectkey: 'your-project-key'
    - name: Add Artifactory details
      uses: artifactory-action@v2
      with:
        token: ${{ secrets.ARTIFACTORY_TOKEN }}
        url: 'http://artifactory.example.com'
    - name: SAST & SCA scan
      uses: squilliam/sonar-sast-scanner@v1
      env:
        SONAR_HOST URL: sonarhost
        SONAR_USERNAME: your-sonar-username
        SONAR_PASSWORD: your-sonar-password