name: SAST-python-demo
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up environment variables
        env:
          PYPROJECT_TOML: ${{ secrets.PYPROJECT_TOML }}
          SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${PYPROJECT_TOML['dependencies']}
      - name: Run build and tests if applicable
        run: |
          python setup.py sdist bdist_wheel
          python -mtwine upload dist/*
          pytest
      - name: Run library list file
        run: |
          pip freeze > requirements.txt
      - name: Add SonarQube details
        uses: sonarqube/sonarqube-action@v2.3.0
        with:
          token: ${{ secrets.SONARQUBE_TOKEN }}
          project-key: ${SONARQUBE_PROJECT_KEY}
          project-name: ${SONARQUBE_PROJECT_NAME}
      - name: Add Artifactory details
        uses: artifactor/sonarqube-artifactory-action@v1.2.0
        with:
          token: ${{ secrets.ARTIFACTORY_TOKEN }}
          repository-name: python-demo
          url: ${ARTIFACTORY_URL}
      - name: Add SAST & SCA scan
        uses: sonarqube/sonarqube-action@v2.3.0
        with:
          token: ${{ secrets.SONARQUBE_TOKEN }}
          project-key: ${SONARQUBE_PROJECT_KEY}
          project-name: ${SONARQUBE_PROJECT_NAME}