name: ms-nginx-app
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        uses: appleboy/env-install@v1
        with:
          env_file: .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build and tests
        run: |
          python setup.py sdist bdist_wheel
          python setup.py test

      - name: List installed libraries
        run: |
          pip freeze > requirements.txt

      - name: Add SonarQube details
        uses: sonarqube/sonarqube-action@v1.2.0
        env:
          SONAR_HOST_URL: 'http://localhost:9000'
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'

      - name: Add Artifactory details
        uses: artifactory/artifactory-action@v3.7.0
        with:
          api_token: '${{ secrets.ARTIFACTORY_API_TOKEN }}'
          server_url: 'https://your-artifactory-server.com'

      - name: Run SAST scan
        uses: squishy-sec/sast-action@v4.1.0
        env:
          SAST_TOKEN: '${{ secrets.SAST_TOKEN }}'

      - name: Run SCA scan
        uses: squishy-sec/sca-action@v2.2.0
        env:
          SCA_TOKEN: '${{ secrets.SCA_TOKEN }}'