name: ${GITHUB_REPOSITORY}

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        export DEPENDENCY_FILE=pyproject.toml
        export LANGUAGE=python

    - name: Install dependencies
      run: python -m pip install --upgrade pip
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

    - name: Run build and tests
      if: succeeded()
      run: |
        python setup.py build
        pytest

    - name: Run library list file
      run: pip freeze > requirements.txt

    - name: Add SonarQube details
      uses: sonarqube/sonarqube-action@v1.3.0
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR Johnson : ${GITHUB_TOKEN}
        SONAR_USERNAME: ${{ secrets.SONAR_USERNAME }}
        SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}

    - name: Add Artifactory details
      uses: artifactory/gradle-artifactory-plugin@v1.2.0
      env:
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

    - name: SAST & SCA scan
      uses: ossf/oss-fhir-scan@v0.5.2
      env:
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}