name: SAST-python-demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ runner.os }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run build and tests if applicable
      env:
        PIP_VERSION: $(pip --version)
      run: |
        if [ ${{ runner.os }} == 'windows' ]; then
          python -m pip install --upgrade pip && pip install -r requirements.txt
        else
          pip install --upgrade pip && pip install -r requirements.txt
        fi
    - name: Run library list file
      run: |
        pip freeze > requirements.txt
    - name: Add SonarQube details
      uses: sonarqube/sonarqube@v2.0.1
      with:
        sonarorg: 'your-sonarqube-instance'
        sonaruser: 'your-username'
        sonarpwd: 'your-password'
    - name: Add Artifactory details
      uses: artifactory/sonatype-artifactor-github-action@v1.0.2
      with:
        username: 'your-username'
        password: 'your-password'
        url: 'https://your-artifactory-instance.com'
    - name: Add SAST & SCA scan 
      uses: sonarqube/sonarqube-github-action@v1.0.2
      with:
        org: 'your-organization'
        project: 'your-project-name'