name: SAST-python-demo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      run: |
        export PATH=$HOME/.local/bin:$PATH
        export PYCHARM_HOSTED=0
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run build and tests if applicable
      run: |
        python setup.py sdist bdist_wheel
        python -m twine upload dist/*
        # Add your tests here
    - name: Run library list file
      run: |
        python -c "import pkg_resources; print('\n'.join(pkg_resources.working_set))" > libraries.txt
    - name: Add SonarQube details
      uses: sonarqube/sonarqube-action@v1.0.2
      with:
        sonarorg: ${{ secrets.SONARORG }}
        sonarprojectkey: ${{ secrets.SONARPROJECTKEY }}
        sonarlogin: ${{ secrets.SONARLOGIN }}
    - name: Add Artifactory details
      uses: artifactory/artifactory-action@v1.0.2
      with:
        username: ${{ secrets.ARTIFACTORY_USERNAME }}
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}
        url: ${{ secrets.ARTIFACTORY_URL }}
    - name: Add SAST & SCA scan
      uses: sonarqube/sonar-sast-scanner-action@v1.4.0
      with:
        sonarorg: ${{ secrets.SONARORG }}
        sonarprojectkey: ${{ secrets.SONARPROJECTKEY }}
        sonarlogin: ${{ secrets.SONARLOGIN }}