name: SAST-python-demo

on:
  push:
    branches:
      - master

jobs:
  sast-python-demo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up the required environment
      run: |
        export DEPENV_FILE=.env

    - name: Install dependencies
      run: pip install --no-cache-dir -r .depenv

    - name: Run build and tests
      run: |
        python setup.py sdist bdist_wheel

    - name: Create library list file
      run: |
        pip freeze > requirements.txt

    - name: Add SonarQube details
      uses: sonarqube/sonar-qube-action@v1.6.0
      with:
        token: ${{ secrets.SONAR_TOKEN }}
        project-name: 'your-project-name'
        project-key: 'your-project-key'

    - name: Add Artifactory details
      uses: artifactory/artifactory-deploy@v2.12.0

    - name: SAST & SCA scan
      uses: sonarcloud/sonarcloud-action@v1.4.0
      with:
        token: ${{ secrets.SONAR_TOKEN }}
        project-name: 'your-project-name'
        project-key: 'your-project-key'