name: SAST-python-demo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up environment
      uses: azure/az-devops-pipelines@v0.1.0
      with:
        azureSubscription: 'your_subscription_name'
        repositoryName: 'your_repository_name'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pyproject.toml
    - name: Build and tests (if applicable)
      if: branches != 'main' && !github.event.project_path
      run: |
        python setup.py build
        python -m unittest discover
    - name: Run library list file
      run: |
        pip freeze > requirements.txt
    - name: Add SonarQube details
      uses: sonarcloud/sonarcloud-github-action@v0.2.0
      with:
        organization: 'your_organisation_name'
        token: '${{ secrets.SONARCLOUD_TOKEN }}'
        projectKey: 'your_project_key'
    - name: Add Artifactory details
      uses: artifactorysteam/artifactory-github-action@v1.0.0
      with:
        username: 'your_username'
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}
        url: 'https://your_artifactory_url.com'
    - name: Add SAST & SCA scan
      uses: sonarcloud/sonarcloud-github-action@v0.2.0
      with:
        organization: 'your_organisation_name'
        token: '${{ secrets.SONARCLOUD_TOKEN }}'
        projectKey: 'your_project_key'