name: SAST-python-demo
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run build and tests
      run: |
        python setup.py build
        python setup.py test
    - name: List library contents
      run: |
        pip freeze > libraries.txt
    - name: Add SonarQube details
      uses: sonarqube/sonarqube-analysis@v1.6
      with:
        org: 'your-organisation'
        project: 'your-project'
        token: ${{ secrets.SONAR_TOKEN }}
    - name: Add Artifactory details
      uses: artifactorysteam/artifactory-deploy@master
      with:
        username: 'your-artifact-username'
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}
        api-key: 'your-api-key'
    - name: SAST & SCA scan
      uses: sonarqube/sonar-scan@v1.6
      with:
        org: 'your-organisation'
        project: 'your-project'
        token: ${{ secrets.SONAR_TOKEN }}