Certainly! Below is a sample GitHub Actions YAML workflow file named `build.yml` that satisfies the requirements you've provided for a Python project using a `pyproject.toml` file.

```yaml
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry  # Assuming you are using Poetry for dependency management
        poetry install

    - name: Run tests
      run: |
        poetry run pytest  # Adjust this command if you are using a different test framework
```

### Explanation of the YAML file:
- **name**: The name of the workflow is set to "CI Pipeline".
- **on**: The workflow triggers on `push` events to the `main` branch and `pull_request` events targeting the `main` branch.
- **jobs**: Defines the CI job named `build`.
- **runs-on**: Specifies the environment in which the job will run; in this case, it uses the latest version of Ubuntu.
- **steps**:
  - **Checkout**: Uses the `actions/checkout` action to pull the latest code from the repository.
  - **Set up Python**: Uses the `actions/setup-python` action to set up the specified Python version.
  - **Install dependencies**: Uses `pip` to upgrade itself and install Poetry. Then it installs the dependencies listed in `pyproject.toml`.
  - **Run tests**: Executes the test suite using `pytest`, which you may need to adjust if you're using a different testing framework.

Make sure to place this `build.yml` file in the `.github/workflows` directory of your repository for it to be recognized by GitHub Actions. Adjust the Python version and testing command according to your project's specific requirements.