name: SAST-python-demo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run build and tests
      if: success()
      run: |
        # Add your build command here, e.g. python setup.py sdist bdist_wheel
    - name: Run library list file
      run: |
        # Add your command to list libraries here
    - name: Set up SonarQube details
      uses: sonarqube/sonarqube-action@v1
      with:
        url: 'your-sonarqube-url'
        username: 'your-username'
        password: 'your-password'
    - name: Add Artifactory details
      uses: artifactory/artifactory-action@v3
      with:
        username: 'your-artifactory-username'
        password: 'your-artifactory-password'
        url: 'your-artifactory-url'
    - name: Add SAST & SCA scan
      uses: sonarqube/sonar-scanner-action@v1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        SONAR_HOSTURL: ${{ secrets.SONAR_HOSTURL }}