name: SAST-python-demo
on:
  push:
    branches:
      - master
jobs:
  python_demo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        export PYPROJECT_TOML=pyproject.toml
        export PYTHONUNBUFFERED=1
        export DEPENDENCY_FILE=pyproject.toml

    - name: Install dependencies
      shell: bash
      run: |
        pip install --no-cache-dir -r $DEPENDENCY_FILE

    - name: Run build and tests if applicable
      shell: bash
      run: |
        python -m pytest

    - name: Check library list file
      run: |
        if [ ! -f requirements.txt ]; then
          echo "Library List file not found."
          exit 1
        fi

    - name: Add SonarQube details
      uses: sonarqube/sonarqube-action@v2
      with:
        sonarorg: 'your-sonarqube-url'
        username: 'your-sonarqube-username'
        password: 'your-sonarqube-password'

    - name: Add Artifactory details
      uses: artifactorystore/artifactory-action@v2
      with:
        username: 'your-artifactory-username'
        password: 'your-artifactory-password'
        url: 'your-artifactory-url'

    - name: SAST & SCA scan
      uses: sonarqube/sonar-sast-and-sca-action@v2
      with:
        sonarorg: 'your-sonarqube-url'
        token: ${{ secrets.SONARQUBE_TOKEN }}
        projectKey: 'your-project-key'